# Generated by Django 4.2.29 on 2026-03-18 14:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Вес')),
                ('volume', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Объём')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_start', models.TextField(verbose_name='Адрес начала')),
                ('address_end', models.TextField(verbose_name='Адрес конца')),
                ('departure_date', models.DateTimeField(verbose_name='Дата отправления')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='TransportType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users', to='gruz_app.role', verbose_name='Роль')),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100, verbose_name='Марка')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
                ('transport_number', models.CharField(max_length=20, unique=True, verbose_name='Номер транспорта')),
                ('capacity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Вместимость')),
                ('transport_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transports', to='gruz_app.transporttype', verbose_name='Тип транспорта')),
            ],
        ),
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время')),
                ('action', models.TextField(verbose_name='Действие')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trackings', to='gruz_app.route', verbose_name='Маршрут')),
            ],
        ),
        migrations.AddField(
            model_name='route',
            name='client',
            field=models.ForeignKey(limit_choices_to={'role__name': 'Клиент'}, on_delete=django.db.models.deletion.PROTECT, related_name='client_routes', to='gruz_app.user', verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='route',
            name='driver',
            field=models.ForeignKey(limit_choices_to={'role__name': 'Водитель'}, on_delete=django.db.models.deletion.PROTECT, related_name='driver_routes', to='gruz_app.user', verbose_name='Водитель'),
        ),
        migrations.AddField(
            model_name='route',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routes', to='gruz_app.status', verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='route',
            name='transport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routes', to='gruz_app.transport', verbose_name='Транспорт'),
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='gruz_app.cargo', verbose_name='Груз')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='gruz_app.route', verbose_name='Маршрут')),
            ],
        ),
    ]
